module.exports={
    devServer:{
        open:true,
        proxy:{
            '/api':{
                target:'http://api.lvluo.com',
                changeOrigon:true,
            }
        }
    }
}