module.exports={
    devServer:{
        open:true,
        proxy:{
            '/api':{
                target:'http://121.42.230.80',
                changeOrigon:true,
            }
        }
    }
}